# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./minio-data-1:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio2:
    image: docker.io/bitnami/minio:2024
    volumes:
      - "./minio-data-2:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio3:
    image: docker.io/bitnami/minio:2024
    volumes:
      - "./minio-data-3:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio4:
    image: docker.io/bitnami/minio:2024
    volumes:
      - "./minio-data-4:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
# volumes:
#   minio_data:
#     driver: local
#   minio_2_data:
#     driver: local
#   minio_3_data:
#     driver: local
#   minio_4_data:
#     driver: local
