# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./minio-data-1:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_STORAGE_CLASS_STANDARD=EC:0
  minio2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./minio-data-2:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_STORAGE_CLASS_STANDARD=EC:0
  minio3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./minio-data-3:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_STORAGE_CLASS_STANDARD=EC:0
  minio4:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./minio-data-4:/bitnami/minio/data"
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_STORAGE_CLASS_STANDARD=EC:0
